# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobol-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobol-app
  template:
    metadata:
      labels:
        app: cobol-app
    spec:
      volumes:
      - name: cobol-data
        persistentVolumeClaim:
          claimName: cobol-data-pvc

      initContainers:
      - name: setup-data
        image: cobol-app:latest
        imagePullPolicy: Never
        command: ['sh', '-c', 'if [ ! -f /data/accounts.txt ]; then cp /workspace/accounts.txt /data/accounts.txt; fi']
        volumeMounts:
        - name: cobol-data
          mountPath: /data

      containers:
      # --- Container 1: The Python Web App (with the fix) ---
      - name: webapp
        image: cobol-app:latest
        imagePullPolicy: Never
        # This command runs before the web server starts.
        # It creates a link from the local path to the shared volume's path,
        # then starts the uvicorn server as normal.
        command: ["/bin/sh", "-c"]
        args:
          - ln -sf /data/accounts.txt /workspace/accounts.txt && uvicorn app:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: cobol-data
          mountPath: /data

      # --- Container 2: The COBOL Interest Calculator (working correctly) ---
      - name: interest
        image: cobol-app:latest
        imagePullPolicy: Never
        workingDir: /data
        command: ["/workspace/main", "--apply-interest"]
        volumeMounts:
        - name: cobol-data
          mountPath: /data